
spring:
    datasource:
        # DataSource settings: set here your own configurations for the database
        # connection. In this example we have "netgloo_blog" as database name and
        # "root" as username and password.
        driverclassname: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test
        username: root
        password: 123456

        # Keep the connection alive if idle for a long time (needed in production)
        testWhileIdle: true
        validationQuery: SELECT 1

    jpa:
        # Show or not log for each sql query
        show-sql: true
        hibernate:
            # Hibernate ddl auto (create, create-drop, update)
            ddl-auto: update
        generate-ddl: true

#spring.jackson.property-naming-strategy=SNAKE_CASE

# Level logging
logging:
    level:
        com.agility.spring: DEBUG
#logging.level.org.springframework.web=DEBUG
#logging.level.root=DEBUG
#logging.file=logs/application.log
#logging.level.org.hibernate=ERROR

# Does not trigger a restart on /static and /public directory

    devtools.restart.exclude: static/**, public/**
