security:
    secret: SecretKeyToGenJWTs
    expiration-time: 864000000
    token-prefix: Bearer
    header-string: Authorization

spring:
    # Specify which profiles are active
    profiles:
        active: dev

    mvc:
        throw-exception-if-no-handler-found: true
    resources:
        add-mappings: false

    # JACKSON
    jackson:
        serialization:
            # Disable converting dates to timestamps and instead use a ISO-8601 compliant format
            write_dates_as_timestamps: false
        # Controls the inclusion of properties during serialization
        default-property-inclusion: non_null
        mapper:
            # Controls properties that have no view associated are serialized
            default_view_inclusion: true

# LEVEL LOGGING
logging:
    level:
        com.agility.usermanagement: DEBUG



