spring:
    # DATASOURCE
    # Set here configurations for the database connection
    datasource:
        # Connection url for the database "user_management"
        url: jdbc:mysql://localhost:3306/user-management-resource

        # MySQL username and password
        username: root
        password: password

        # Keep the connection alive if idle for a long time (needed in production)
        test-while-idle: true
        validation-query: SELECT 1

# LEVEL LOGGING
logging:
    level:
        org.hibernate.stat: true
        org.hibernate.type: trace