create table category (id bigint not null auto_increment, description varchar(255), primary key (id)) engine=MyISAM;
create table ingredient (id bigint not null auto_increment, amount decimal(19,2), description varchar(255), recipe_id bigint, uom_id bigint, primary key (id)) engine=MyISAM;
create table notes (id bigint not null auto_increment, recipe_notes longtext, recipe_id bigint, primary key (id)) engine=MyISAM;
create table recipe (id bigint not null auto_increment, cook_time integer, description varchar(255), difficulty varchar(255), directions longtext, image longblob, prep_time integer, servings integer, source varchar(255), url varchar(255), notes_id bigint, primary key (id)) engine=MyISAM;
create table recipe_categories (recipe_id bigint not null, category_id bigint not null, primary key (recipe_id, category_id)) engine=MyISAM;
create table unit_of_measure (id bigint not null auto_increment, description varchar(255), primary key (id)) engine=MyISAM;
alter table ingredient add constraint FKj0s4ywmqqqw4h5iommigh5yja foreign key (recipe_id) references recipe (id);
alter table ingredient add constraint FK6iv5l89qmitedn5m2a71kta2t foreign key (uom_id) references unit_of_measure (id);
alter table notes add constraint FKdbfsiv21ocsbt63sd6fg0t3c8 foreign key (recipe_id) references recipe (id);
alter table recipe add constraint FK37al6kcbdasgfnut9xokktie9 foreign key (notes_id) references notes (id);
alter table recipe_categories add constraint FK6pvvs3ogtv1r4nnnff6tdse11 foreign key (category_id) references category (id);
alter table recipe_categories add constraint FKf9uxi3701as945rybpx129buq foreign key (recipe_id) references recipe (id);
